import { StyleSheet } from 'react-native';

/** Shared across the four guardian-journey screens so they read as one flow. */
export const minorStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FB' },
  centre: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  header: { padding: 24, paddingTop: 60, paddingBottom: 12 },
  step: { color: '#F7941E', fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  title: { color: '#102A54', fontSize: 24, fontWeight: '800', marginTop: 8 },
  subtitle: { color: '#4A5568', fontSize: 14, marginTop: 8, lineHeight: 20 },
  content: { paddingHorizontal: 20 },
  label: { fontSize: 13, color: '#4A5568', fontWeight: '600', marginTop: 18, marginBottom: 6 },
  input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, minHeight: 52, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, color: '#102A54' },
  multiline: { minHeight: 90, textAlignVertical: 'top' },
  hint: { color: '#718096', fontSize: 11, marginTop: 6, lineHeight: 16 },
  chipRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  chip: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 10 },
  chipSelected: { backgroundColor: '#3C3985', borderColor: '#3C3985' },
  chipText: { color: '#4A5568', fontWeight: '700', fontSize: 13 },
  chipTextSelected: { color: '#fff', fontWeight: '700', fontSize: 13 },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#E2E8F0', marginTop: 16 },
  cardTitle: { color: '#102A54', fontSize: 15, fontWeight: '800', marginBottom: 8 },
  bodyText: { color: '#4A5568', fontSize: 13, lineHeight: 20 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12 },
  rowLabel: { color: '#4A5568', fontSize: 14, fontWeight: '600' },
  rowValue: { color: '#102A54', fontSize: 14, fontWeight: '700' },
  ok: { color: '#38A169' },
  pending: { color: '#C05621' },
  consentRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 20, gap: 12 },
  checkbox: { width: 24, height: 24, borderRadius: 6, borderWidth: 2, borderColor: '#CBD5E0', alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  checkboxChecked: { backgroundColor: '#3C3985', borderColor: '#3C3985' },
  checkIcon: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  consentText: { flex: 1, color: '#4A5568', fontSize: 13, lineHeight: 19 },
  button: { backgroundColor: '#3C3985', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 28 },
  buttonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  outlineButton: { padding: 16, borderRadius: 12, alignItems: 'center', borderWidth: 2, borderColor: '#3C3985', marginTop: 12 },
  outlineText: { color: '#3C3985', fontSize: 15, fontWeight: '700' },
  disabled: { opacity: 0.5 },
  error: { color: '#C53030', fontSize: 13, marginTop: 12 },
  spacer: { height: 48 },
});
