export const RISK_ASSESSMENT_VERSION = '2026.08.12Q';

export const RISK_QUESTIONS = [
  { id: 'age', dimension: 'Age', prompt: 'What is your age group?', options: [{ label: 'Above 50 years', score: 1 }, { label: '36 - 50 years', score: 2 }, { label: '25 - 35 years', score: 3 }, { label: 'Below 25 years', score: 4 }] },
  { id: 'horizon', dimension: 'Investment horizon', prompt: 'For how long do you plan to stay invested?', options: [{ label: 'Less than 1 year', score: 1 }, { label: '1 to 3 years', score: 2 }, { label: '3 to 7 years', score: 3 }, { label: 'More than 7 years', score: 4 }] },
  { id: 'income', dimension: 'Income', prompt: 'What is your monthly household income?', options: [{ label: 'Below ₹15,000', score: 1 }, { label: '₹15,000 - ₹30,000', score: 2 }, { label: '₹30,000 - ₹60,000', score: 3 }, { label: 'Above ₹60,000', score: 4 }] },
  { id: 'income_source', dimension: 'Income source', prompt: 'My current and future source of income are', options: [{ label: 'Very unstable', score: 1 }, { label: 'Unstable', score: 2 }, { label: 'Somewhat stable', score: 3 }, { label: 'Stable', score: 4 }, { label: 'Very Stable', score: 5 }] },
  { id: 'preference', dimension: 'Investment preference', prompt: 'Choose your investment preference/Objective', options: [{ label: 'Principal protection', score: 1 }, { label: 'Can consider a loss of 4% if the expected gains are of 10%', score: 2 }, { label: 'Can consider a loss of 8% if the expected gains are of 20%', score: 3 }, { label: 'Can consider a loss of 15% if the expected gains are of 30%', score: 4 }, { label: 'Can consider a loss of 25% if the expected gains are of 50%', score: 5 }] },
  { id: 'decline_reaction', dimension: 'Market reaction', prompt: 'If a few months after investing, the value of your portfolio goes down due to market decline by 20%, what would you do?', options: [{ label: 'Cut losses and Sell completely', score: 1 }, { label: 'Sell partially and transfer investments to safer asset classes', score: 2 }, { label: 'You would be worried, but would give your investments a little more time', score: 3 }, { label: 'Retain fully, you are OK with volatility and accept decline', score: 4 }, { label: 'Buy more to bring down the average buying price', score: 5 }] },
  { id: 'tax_efficiency', dimension: 'Tax efficiency', prompt: 'Volatile investments usually provide higher returns and tax efficiency. What is your desired balance?', options: [{ label: 'Preferably guaranteed returns, before tax efficiency', score: 1 }, { label: 'Stable returns, minimal tax efficiency', score: 2 }, { label: 'Some variability in returns, some tax efficiency', score: 3 }, { label: 'Moderate variability in returns, reasonable tax efficiency', score: 4 }, { label: 'Unstable but potentially higher returns, maximising tax efficiency', score: 5 }] },
  { id: 'familiarity', dimension: 'Investment experience', prompt: 'How familiar are you with financial markets?', options: [{ label: 'I have no idea about financial markets', score: 1 }, { label: 'I have very basic idea about investing & no experience', score: 2 }, { label: 'I have a fair knowledge & experience', score: 3 }, { label: 'I have thorough knowledge & experience', score: 4 }] },
  { id: 'risk_range', dimension: 'Risk range', prompt: 'Describe your Risk Range. What level of losses and profits you would be comfortable with?', options: [{ label: 'Worst Year = 1% and Best Year = 15%', score: 1 }, { label: 'Worst Year = -5% and Best Year = 20%', score: 2 }, { label: 'Worst Year = -10% and Best Year = 25%', score: 3 }, { label: 'Worst Year = -15% and Best Year = 30%', score: 4 }, { label: 'Worst Year = -18% and Best Year = 35%', score: 5 }, { label: 'Worst Year = -22% and Best Year = 45%', score: 5 }] },
  { id: 'dependents', dimension: 'Financial responsibility', prompt: 'How many financial dependents do you have?', options: [{ label: 'More than 3', score: 1 }, { label: '2 to 3', score: 2 }, { label: '1', score: 3 }, { label: 'None', score: 4 }] },
  { id: 'liabilities', dimension: 'Liabilities', prompt: 'What percentage of your income goes towards paying off loans/EMIs?', options: [{ label: 'More than 50%', score: 1 }, { label: '30% to 50%', score: 2 }, { label: '10% to 30%', score: 3 }, { label: 'Less than 10% or None', score: 4 }] },
  { id: 'emergency_fund', dimension: 'Emergency Fund', prompt: 'How many months of expenses do you have saved in an emergency fund?', options: [{ label: 'Less than 1 month', score: 1 }, { label: '1 to 3 months', score: 2 }, { label: '3 to 6 months', score: 3 }, { label: 'More than 6 months', score: 4 }] }
] as const;
